<a href="https://colab.research.google.com/github/navap3206-debug/hello-world/blob/main/A03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [128]:
import pandas as pd
from google.colab import files

PREPARACIÓM DE LOS DATOS

In [129]:
dt = files.upload()
df = pd.read_csv('feo.csv', encoding='latin-1')

df.head(100)

Saving feo.csv to feo (13).csv

   TAMAÑO HIELO     SABOR  SCORE  KAHLUA  HORCHATA
0  grande   sin    Kahlua    8.2       1         0
1  grande   con    Kahlua    9.0       1         0
2   chica   sin    Kahlua    7.0       1         0
3   chica   con    Kahlua    7.5       1         0
4  grande   con  Horchata   10.0       0         1
5  chica    sin  Horchata    6.0       0         1
6   chica   con  Horchata    6.4       0         1
7  grande   sin  Horchata    9.5       0         1

TRANFORMAMOS A BINARIO

In [130]:
df['KAHLUA'] = (df['SABOR'] == 'Kahlua').astype(int)
df['HORCHATA'] = (df['SABOR'] == 'Horchata').astype(int)
df['HIELO'] = (df['HIELO'] == 'con').astype(int)
df['TAMAÑO'] = (df['TAMAÑO'] == 'grande').astype(int)

In [131]:
df.drop(columns=['SABOR'], inplace=True)

In [132]:

df.head(8)

   TAMAÑO  HIELO  SCORE  KAHLUA  HORCHATA
0       1      0    8.2       1         0
1       1      1    9.0       1         0
2       0      0    7.0       1         0
3       0      1    7.5       1         0
4       1      1   10.0       0         1
5       0      0    6.0       0         1
6       0      1    6.4       0         1
7       1      0    9.5       0         1

In [133]:
import numpy as np
from sklearn.linear_model import LinearRegression
#TRANSFORMAMOS A UNA MATRIZ MANIPULABLE

X_matrix = df[['TAMAÑO', 'HIELO', 'KAHLUA', 'HORCHATA']].to_numpy()
Y_vec = df['SCORE'].to_numpy()

lr = LinearRegression(fit_intercept= True)
lr.fit(X_matrix, Y_vec)
lr.intercept_

np.float64(6.449999999999999)

In [134]:
lr.intercept_

np.float64(6.449999999999999)

In [135]:
lr.coef_

array([ 2.45 ,  0.55 , -0.025,  0.025])

In [136]:
#con summary
import statsmodels.api as SM
X2 = SM.add_constant(X_matrix)
model = SM.OLS(Y_vec,X2)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.837
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     6.824
Date:                Tue, 10 Feb 2026   Prob (F-statistic):             0.0473
Time:                        00:06:28   Log-Likelihood:                -6.6425
No. Observations:                   8   AIC:                             21.29
Df Residuals:                       4   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.3000      0.320     13.417      0.000       3.410       5.190
x1             2.4500      0.555      4.414      0.012       0.909       3.991
x2             0.5500      0.555      0.991      0.378      -0.991       2.091
x3             2.1250      0.320      6.631      0.003       1.235       3.015
x4             2.1750      0.320      6.787      0.002       1.285       3.065
==============================================================================
Omnibus:                        7.172   Durbin-Watson:                   1.431
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                1.242
Skew:                          -0.048   Prob(JB):                        0.537
Kurtosis:                       1.072   Cond. No.                     2.22e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.37e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

PARTE 2 (MODIFICAMOS LOS CATEGORICOS DE TIPO 1,-1

In [137]:
df['HIELO'] = df['HIELO'].replace(0,-1)
df['TAMAÑO'] = df['TAMAÑO'].replace(1,-1)
df['TAMAÑO'] = df['TAMAÑO'].replace(0,1)
df

   TAMAÑO  HIELO  SCORE  KAHLUA  HORCHATA
0      -1     -1    8.2       1         0
1      -1      1    9.0       1         0
2       1     -1    7.0       1         0
3       1      1    7.5       1         0
4      -1      1   10.0       0         1
5       1     -1    6.0       0         1
6       1      1    6.4       0         1
7      -1     -1    9.5       0         1

In [138]:
X_matrix_2 = df[['TAMAÑO', 'HIELO', 'KAHLUA', 'HORCHATA']].to_numpy()
Y_vec = df['SCORE'].to_numpy()

In [139]:
#con summary
import statsmodels.api as SM
X2 = SM.add_constant(X_matrix_2) #CONCADENAR
model = SM.OLS(Y_vec,X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results_2 = model.fit() #OPTIMIZA
print(results_2.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.837
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     6.824
Date:                Tue, 10 Feb 2026   Prob (F-statistic):             0.0473
Time:                        00:06:28   Log-Likelihood:                -6.6425
No. Observations:                   8   AIC:                             21.29
Df Residuals:                       4   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3000      0.185     28.644      0.000       4.786       5.814
x1            -1.2250      0.278     -4.414      0.012      -1.996      -0.454
x2             0.2750      0.278      0.991      0.378      -0.496       1.046
x3             2.6250      0.293      8.973      0.001       1.813       3.437
x4             2.6750      0.293      9.143      0.001       1.863       3.487
==============================================================================
Omnibus:                        7.172   Durbin-Watson:                   1.431
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                1.242
Skew:                          -0.048   Prob(JB):                        0.537
Kurtosis:                       1.072   Cond. No.                     1.84e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.54e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [140]:
print(results.params)
print(results_2.params)

[4.3   2.45  0.55  2.125 2.175]
[ 5.3   -1.225  0.275  2.625  2.675]

INTERPRETACIÓN

A primera vista algunos indicadores como R2 no tienen modificaciones lo cual nos habla de que por mucho que modifiquemos los datos estamos trabajando con el mismo caso, sin embargo tenemos un intercepto que se recorre según el peso de los elementos; de igual forma debido a que la distiancia o escala de la prueba dos es mayor, tenemos algunos coeficientes (Tamaño y hielo)en una escala practicamente por mitad a la original debido al cambio.